#!/bin/sh
# ~/.config/openbox/autostart | Curtis Free (http://curtisfree.com)

# Export(s)
export OOO_FORCE_DESKTOP=gnome

# Terminal Daemon
urxvtd -q -o -f

# ~/.gtkrc-2.0 "hack"
if [ -f ~/.gtkrc-2.0.openbox ]; then
    mv ~/.gtkrc-2.0.openbox ~/.gtkrc-2.0
fi

# Filesystem Setup
## Firefox Cache
### See http://wiki.archlinux.org/index.php/Speed-up_Firefox_using_tmpfs.
install -dm700 /dev/shm/firefox-cache

# Post-start Application(s)

## Wallpaper
~/scripts/wm/randesk.py

## Panel
(sleep 1 && type tint2 &>/dev/null && tint2) &

## System Monitor (Optional)
(type conky &>/dev/null && conky -q) &

## Cursor Hiding (Optional)
### See http://wiki.archlinux.org/index.php/Unclutter.
(type unclutter &>/dev/null && unclutter -idle 3) &

## Clipboard Sync
### See http://superuser.com/questions/68170/how-can-i-merge-the-gnome-clipboard-and-the-x-selection.
(type autocutsel &>/dev/null && autocutsel -fork && autocutsel -fork -s PRIMARY)

